### PR TITLE
Feat label clean

### PR DESCRIPTION
**Pull request by AmandaLinLi**

### CODE REVIEW

**Comment by wibeasley** [comment]
hi @AmandaLinLi.  Thanks for the contribution.  I see you're working out some issues with RCMD check right now, so I'll wait to comment until that stabilizes.

In the meantime, I see three things to mention now:

### magrittr pipes

All my local code uses R's native pipe released 1+ year ago (ie `|>`) instead of magrittr's pipe (ie, `%>%`).  But some REDCapR users can't or won't upgrade to R 4.1 yet (ahem, @andkov).  So I think we'll stick with magrittr for another year or two.

### Package dependencies
tAt least one of those errors is caused because your new function calls packages that aren't existing dependencies of REDCapR, such as textclean, stringr, and stringi.  I'd prefer not to have them as dependencies because they're really heavy, with a lot of dependencies themselves.  

See what you can do with base functions `sub()` and `gsub()`.  For instance, `stringr::str_remove_all(field_label_new, "_x000D_")` can potentially be replaced by `sub(field_label_new, "_x000D_", "")`.  Also try replacing `stringi::stri_replace_all_fixed(field_label_new, " .",  ".") ` with `gsub(field_label_new, " \\.",  ".") `.

I haven't ready what the two textclean functions do, but I'm hesitant to depend on something that hasn't been updated on CRAN in 4 years.  Even if the function are perfect, there's always little update that CRAN requires and they remove old packages with <14 days warning.

https://github.com/OuhscBbmc/REDCapR/runs/7978297221?check_suite_focus=true#step:6:77

### Write tests

Sometimes if you run REDCapR checks on multiple machines in the same time, the checks/tests will fail because their reading & writing from the same project simultaneously.  If you think this is happening, you can request that GitHub rerun the job.

**Comment by AmandaLinLi** [comment]
Hello Will,

Thanks so much for your response and comments. I will address the errors/warning.

My main intention to add the feature is to clean field_labels with html tags, and  separate the labels in different languages (I.e English/español), if there is any.

Best
Amanda

Sent from my “Artificial Idiot(AI)” iPhone. Please excuse brevity and any typos.
________________________________

**Comment by AmandaLinLi** [comment]
> hi @AmandaLinLi. Thanks for the contribution. I see you're working out some issues with RCMD check right now, so I'll wait to comment until that stabilizes.
> 
> In the meantime, I see three things to mention now:
> 
> ### magrittr pipes
> All my local code uses R's native pipe released 1+ year ago (ie `|>`) instead of magrittr's pipe (ie, `%>%`). But some REDCapR users can't or won't upgrade to R 4.1 yet (ahem, @andkov). So I think we'll stick with magrittr for another year or two.
> 
> ### Package dependencies
> tAt least one of those errors is caused because your new function calls packages that aren't existing dependencies of REDCapR, such as textclean, stringr, and stringi. I'd prefer not to have them as dependencies because they're really heavy, with a lot of dependencies themselves.
> 
> See what you can do with base functions `sub()` and `gsub()`. For instance, `stringr::str_remove_all(field_label_new, "_x000D_")` can potentially be replaced by `sub(field_label_new, "_x000D_", "")`. Also try replacing `stringi::stri_replace_all_fixed(field_label_new, " .", ".") ` with `gsub(field_label_new, " \\.", ".") `.
> 
> I haven't ready what the two textclean functions do, but I'm hesitant to depend on something that hasn't been updated on CRAN in 4 years. Even if the function are perfect, there's always little update that CRAN requires and they remove old packages with <14 days warning.
> 
> https://github.com/OuhscBbmc/REDCapR/runs/7978297221?check_suite_focus=true#step:6:77
> 
> ### Write tests
> Sometimes if you run REDCapR checks on multiple machines in the same time, the checks/tests will fail because their reading & writing from the same project simultaneously. If you think this is happening, you can request that GitHub rerun the job.

Hello Will,

RCMD check issues have been resolved, I followed your 3 comments, I replace `textclean::` with `rvest`, which is newer and smaller. Also, I replace `stringr::`, `stringi::` with the `gsub()` and `sub()` of R `base::` 

P.S: one of the contributor name Janosch L. is my team leader. We are from a UCSD data science group  :)

**Comment by wibeasley** [comment]
@AmandaLinLi, It looks like you're still experimenting with the function's code and interface.  I'm going to close this PR so the ~13 people on the repo's watch list don't get notified for each commit to this PR.

Please tell me when the experimenting is complete and create a new PR.  It may make sense for us to meet too.  I have some question how it can fit best within the package and provide a consistent experience for the users.

**Comment by AmandaLinLi** [comment]
Ok, got you. Sorry for the inconvenience

Sent from my “Artificial Idiot(AI)” iPhone. Please excuse brevity and any typos.
________________________________

**Pull request closed without merging**
