### PR TITLE
Fix metadata forms filter

### LINKED ISSUE #431: Unexpected Behavior: redcap_metadata_read doesn't limit forms when forms parameter is used
**Describe the behavior**:
When an argument is passed in the `forms` parameter to `redcap_metadata_read()`, the metadata for all forms in the project is returned.

Reprex using dummy `REDCapR` dummy project:

```r
# uri and token from ?redcap_metadata_read examples
uri   <- "https://bbmc.ouhsc.edu/redcap/api/"
token <- "9A81268476645C4E5F03428B8AC3AA7B"
resp <- REDCapR::redcap_metadata_read(redcap_uri=uri,
                                      token=token,
                                      # name of a single form in the example data
                                      forms = "health")$data

all(resp$form_name == "health")
#> FALSE
```

**Expected behavior**:
Metadata for only the specified forms ("health" in this case) is returned

**Additional Info**
The problem may be related to how the REDCap API expects the `form` to be passed. For a different test REDCap in our REDCap instance, the API playground suggests:

```r
token <- # [REDACTED]
url <- # [REDACTED]
formData <- list("token"=token,
    content='metadata',
    format='json',
    returnFormat='json',
    'forms[0]'='first_form',      # Look here :)
    'forms[1]'='second_form'
)
response <- httr::POST(url, body = formData, encode = "form")
result <- httr::content(response)
print(result)
```  

Using the `forms[index]` style for the example in my reprex seems to work:

Works:
api-works

Doesn't work:
api-fails

Shareable Postman collection containing those 2 api calls for reproducibility: https://www.getpostman.com/collections/dc243e2bacef264725c1

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - REDCap version 12.5.8
 - REDCapR Version 1.1.0

### PR DESCRIPTION
**Pull request by ezraporter**
Closes #431 

This PR fixes the issue with `redcap_metadata_read` returning all forms when specific forms are requested in the `forms` parameter. In doing this I also noticed that the same bug applies to the `fields` parameter so I implemented the fix there as well.

My solution was to add a small utility function to `redcap-metadata-read.R` that converts a vector into the right format, a list of key-value pairs to append to the request body.

### CODE REVIEW

**Comment by wibeasley** [comment]
Thanks for doing this, @ezraporter.  I was tweaking some of the test projects last night, so there might be some failures unrelated to your changes.  I'll take care of those, if so.

**Comment by ezraporter** [comment]
No problem! I got `R CMD check` to pass locally so we may be in good shape but you never know :)

**Comment by wibeasley** [comment]
Looks good, @ezraporter.  I'll tweak some things like adding checkmate statements and unit tests.

Will you tell me your ORCiD (eg, [Stephan's](https://orcid.org/0000-0003-2996-8034)) for the description file?

**Comment by ezraporter** [comment]
> 1. Will you tell me your ORCiD (eg, [Stephan's](https://orcid.org/0000-0003-2996-8034)) for the description file?

This is me: https://orcid.org/0000-0002-4690-8343

> 2. What do you mean by these comments?  Isn't it ok if someone wants to pass either the fields or the forms, but not both?
>    ```r
>    # append forms and fields arrays in format expected by REDCap API
>    # If either is NULL nothing will be appended
>    post_body <- c(post_body, fields_array, forms_array)
>    ```

Ah that is a poorly worded comment. The behavior is what you described. Someone can pass either one and the right thing will get into `post_body`. I was just reminding myself that `c(some_object, NULL)` yields `c(some_object)` so this behaves correctly if, for examples, `fields_array` is `NULL`.

**Pull request merged**
