### PR TITLE
possible solution for downloading file from repeated instrument

### PR DESCRIPTION
**Pull request by zhangrz2019**
```r
##-----testing file download from repeated instrument in REDCap-----##
##------------------------------------------------------------------##

##-----library-----##
library(REDCapR);

##-----testing function-----##
redcap_download_file_oneshot2 = function (file_name = NULL, directory = NULL, 
                                          overwrite = FALSE, redcap_uri, token, record,
                                          field, event = "", 
                                          repeat_instrument = NULL,
                                          repeat_instance = NULL,
                                          verbose = TRUE, 
                                          config_options = NULL) 
{
    checkmate::assert_character(file_name, null.ok = TRUE, len = 1, 
                                pattern = "^.{1,}$")
    checkmate::assert_character(directory, null.ok = TRUE, len = 1, 
                                pattern = "^.{1,}$")
    checkmate::assert_logical(overwrite, any.missing = FALSE)
    checkmate::assert_character(redcap_uri, any.missing = FALSE, 
                                len = 1, pattern = "^.{1,}$")
    checkmate::assert_character(token, any.missing = FALSE, len = 1, 
                                pattern = "^.{1,}$")
    record <- as.character(record)
    checkmate::assert_character(record, any.missing = FALSE, 
                                len = 1, pattern = "^.{1,}$")
    checkmate::assert_character(field, any.missing = FALSE, len = 1, 
                                pattern = "^.{1,}$")
    validate_field_names(field, stop_on_error = TRUE)
    checkmate::assert_character(event, any.missing = FALSE, len = 1, 
                                pattern = "^.{0,}$")
    checkmate::assert_logical(verbose, any.missing = FALSE)
    token <- sanitize_token(token)
    verbose <- REDCapR:::verbose_prepare(verbose)
    post_body <- list(token = token, content = "file", 
                      action = "export", record = record, field = field, 
                      returnFormat = "csv")
    if (0L < nchar(event)) 
        post_body$event <- event
    if (!is.null(repeat_instrument)) {
        if (is.null(repeat_instance)) {
            stop("You must specify repeat_instance when specified repeat_instrement");
        }
        post_body$repeat_instrument = repeat_instrument;
        post_body$repeat_instance = repeat_instance;
    }
    kernel <- REDCapR:::kernel_api(redcap_uri, post_body, config_options)
    if (kernel$success) {
        result_header <- kernel$result_headers$`content-type`
        if (missing(file_name) | is.null(file_name)) {
            regex_matches <- regmatches(kernel$result_headers, 
                                        regexpr("name=.*", kernel$result_headers))
            file_name <- gsub(pattern = "(name=.)|(\")", 
                              replacement = "", x = regex_matches)
        }
        file_path <- if (missing(directory) & is.null(directory)) {
            file_name
        }
        else {
            file.path(directory, file_name)
        }
        if (verbose) 
            message("Preparing to download the file `", 
                    file_path, "`.")
        if (!overwrite & file.exists(file_path)) {
            stop("The operation was halted because the file `", 
                 file_path, "` already exists and `overwrite` is FALSE.  ", 
                 "Please check the directory if you believe this is a mistake.")
        }
        writeBin(httr::content(kernel$result, as = "raw"), 
                 con = file_path)
        outcome_message <- sprintf("%s successfully downloaded in %0.1f seconds, and saved as %s.", 
                                   result_header, kernel$elapsed_seconds, file_path)
        records_affected_count <- length(record)
        record_id <- as.character(record)
        kernel$raw_text <- ""
    }
    else {
        outcome_message <- "file NOT downloaded."
        records_affected_count <- 0L
        record_id <- character(0)
        file_path <- character(0)
    }
    if (verbose) 
        message(outcome_message)
    list(success = kernel$success, status_code = kernel$status_code, 
         outcome_message = outcome_message, records_affected_count = records_affected_count, 
         affected_ids = record_id, elapsed_seconds = kernel$elapsed_seconds, 
         raw_text = kernel$raw_text, file_name = file_name, file_path = file_path)
}

##-----testing: API: extract files from REDCap database-----##
#redcap_download_file_oneshot(
#   directory = paste(getwd(), "/files", sep = ""),
#   redcap_uri = <URI>,
#   token = <Token>,
#   overwrite = T,
#   record = <record_id>,
#   field = <field name>,
#   event = <redcap_event_name>, 
#   verbose = T
#)

#redcap_download_file_oneshot2(
#   directory = paste(getwd(), "/files", sep = ""),
#   redcap_uri = <URI>,
#   token = <Token>,
#   overwrite = T,
#   record = <record_id>,
#   field = <field name>,
#   event = <redcap_event_name>, 
#   repeat_instrument = <redcap_repeat_instrument>,
#   repeat_instance = <redcap_repeat_instance>,
#   verbose = T
#)
```

### CODE REVIEW

**Comment by zhangrz2019** [comment]
Sorry, I am new to this function:
The code should look like the following:
`redcap_download_file_oneshot2 = function (file_name = NULL, directory = NULL, 
                                          overwrite = FALSE, redcap_uri, 
                                          token, record,
                                          field, event = "", 
                                          repeat_instrument = NULL,
                                          repeat_instance = NULL,
                                          verbose = TRUE, 
                                          config_options = NULL) 
{
    checkmate::assert_character(file_name, null.ok = TRUE, len = 1, 
                                pattern = "^.{1,}$")
    checkmate::assert_character(directory, null.ok = TRUE, len = 1, 
                                pattern = "^.{1,}$")
    checkmate::assert_logical(overwrite, any.missing = FALSE)
    checkmate::assert_character(redcap_uri, any.missing = FALSE, 
                                len = 1, pattern = "^.{1,}$")
    checkmate::assert_character(token, any.missing = FALSE, len = 1, 
                                pattern = "^.{1,}$")
    record <- as.character(record)
    checkmate::assert_character(record, any.missing = FALSE, 
                                len = 1, pattern = "^.{1,}$")
    checkmate::assert_character(field, any.missing = FALSE, len = 1, 
                                pattern = "^.{1,}$")
    validate_field_names(field, stop_on_error = TRUE)
    checkmate::assert_character(event, any.missing = FALSE, len = 1, 
                                pattern = "^.{0,}$")
    checkmate::assert_logical(verbose, any.missing = FALSE)
    token <- sanitize_token(token)
    verbose <- REDCapR:::verbose_prepare(verbose)
    post_body <- list(token = token, content = "file", 
                      action = "export", record = record, field = field, 
                      returnFormat = "csv")
    if (0L < nchar(event)) 
        post_body$event <- event
    if (!is.null(repeat_instrument)) {
        if (is.null(repeat_instance)) {
            stop("You must specify repeat_instance when specified repeat_instrement");
        }
        post_body$repeat_instrument = repeat_instrument;
        post_body$repeat_instance = repeat_instance;
    }
    kernel <- REDCapR:::kernel_api(redcap_uri, post_body, config_options)
    if (kernel$success) {
        result_header <- kernel$result_headers$`content-type`
        if (missing(file_name) | is.null(file_name)) {
            regex_matches <- regmatches(kernel$result_headers, 
                                        regexpr("name=.*", kernel$result_headers))
            file_name <- gsub(pattern = "(name=.)|(\")", 
                              replacement = "", x = regex_matches)
        }
        file_path <- if (missing(directory) & is.null(directory)) {
            file_name
        }
        else {
            file.path(directory, file_name)
        }
        if (verbose) 
            message("Preparing to download the file `", 
                    file_path, "`.")
        if (!overwrite & file.exists(file_path)) {
            stop("The operation was halted because the file `", 
                 file_path, "` already exists and `overwrite` is FALSE.  ", 
                 "Please check the directory if you believe this is a mistake.")
        }
        writeBin(httr::content(kernel$result, as = "raw"), 
                 con = file_path)
        outcome_message <- sprintf("%s successfully downloaded in %0.1f seconds, and saved as %s.", 
                                   result_header, kernel$elapsed_seconds, file_path)
        records_affected_count <- length(record)
        record_id <- as.character(record)
        kernel$raw_text <- ""
    }
    else {
        outcome_message <- "file NOT downloaded."
        records_affected_count <- 0L
        record_id <- character(0)
        file_path <- character(0)
    }
    if (verbose) 
        message(outcome_message)
    list(success = kernel$success, status_code = kernel$status_code, 
         outcome_message = outcome_message, records_affected_count = records_affected_count, 
         affected_ids = record_id, elapsed_seconds = kernel$elapsed_seconds, 
         raw_text = kernel$raw_text, file_name = file_name, file_path = file_path)
}`

**Comment by zhangrz2019** [comment]
For some reason, this code do not appear to be in the correct format:

`redcap_download_file_oneshot2 = function (file_name = NULL, directory = NULL, 
                                          overwrite = FALSE, redcap_uri, 
                                          token, record,
                                          field, event = "", 
                                          repeat_instrument = NULL,
                                          repeat_instance = NULL,
                                          verbose = TRUE, 
                                          config_options = NULL) 
{
    checkmate::assert_character(file_name, null.ok = TRUE, len = 1, 
                                pattern = "^.{1,}$")
    checkmate::assert_character(directory, null.ok = TRUE, len = 1, 
                                pattern = "^.{1,}$")
    checkmate::assert_logical(overwrite, any.missing = FALSE)
    checkmate::assert_character(redcap_uri, any.missing = FALSE, 
                                len = 1, pattern = "^.{1,}$")
    checkmate::assert_character(token, any.missing = FALSE, len = 1, 
                                pattern = "^.{1,}$")
    record <- as.character(record)
    checkmate::assert_character(record, any.missing = FALSE, 
                                len = 1, pattern = "^.{1,}$")
    checkmate::assert_character(field, any.missing = FALSE, len = 1, 
                                pattern = "^.{1,}$")
    validate_field_names(field, stop_on_error = TRUE)
    checkmate::assert_character(event, any.missing = FALSE, len = 1, 
                                pattern = "^.{0,}$")
    checkmate::assert_logical(verbose, any.missing = FALSE)
    token <- sanitize_token(token)
    verbose <- REDCapR:::verbose_prepare(verbose)
    post_body <- list(token = token, content = "file", 
                      action = "export", record = record, field = field, 
                      returnFormat = "csv")
    if (0L < nchar(event)) 
        post_body$event <- event
    if (!is.null(repeat_instrument)) {
        if (is.null(repeat_instance)) {
            stop("You must specify repeat_instance when specified repeat_instrement");
        }
        post_body$repeat_instrument = repeat_instrument;
        post_body$repeat_instance = repeat_instance;
    }
    kernel <- REDCapR:::kernel_api(redcap_uri, post_body, config_options)
    if (kernel$success) {
        result_header <- kernel$result_headers$`content-type`
        if (missing(file_name) | is.null(file_name)) {
            regex_matches <- regmatches(kernel$result_headers, 
                                        regexpr("name=.*", kernel$result_headers))
            file_name <- gsub(pattern = "(name=.)|(\")", 
                              replacement = "", x = regex_matches)
        }
        file_path <- if (missing(directory) & is.null(directory)) {
            file_name
        }
        else {
            file.path(directory, file_name)
        }
        if (verbose) 
            message("Preparing to download the file `", 
                    file_path, "`.")
        if (!overwrite & file.exists(file_path)) {
            stop("The operation was halted because the file `", 
                 file_path, "` already exists and `overwrite` is FALSE.  ", 
                 "Please check the directory if you believe this is a mistake.")
        }
        writeBin(httr::content(kernel$result, as = "raw"), 
                 con = file_path)
        outcome_message <- sprintf("%s successfully downloaded in %0.1f seconds, and saved as %s.", 
                                   result_header, kernel$elapsed_seconds, file_path)
        records_affected_count <- length(record)
        record_id <- as.character(record)
        kernel$raw_text <- ""
    }
    else {
        outcome_message <- "file NOT downloaded."
        records_affected_count <- 0L
        record_id <- character(0)
        file_path <- character(0)
    }
    if (verbose) 
        message(outcome_message)
    list(success = kernel$success, status_code = kernel$status_code, 
         outcome_message = outcome_message, records_affected_count = records_affected_count, 
         affected_ids = record_id, elapsed_seconds = kernel$elapsed_seconds, 
         raw_text = kernel$raw_text, file_name = file_name, file_path = file_path)
}`

**Comment by zhangrz2019** [comment]
Let me try this again, see if the code is in correct format or not:

redcap_download_file_oneshot2 = function (file_name = NULL, directory = NULL, 
                                          overwrite = FALSE, redcap_uri, 
                                          token, record,
                                          field, event = "", 
                                          repeat_instrument = NULL,
                                          repeat_instance = NULL,
                                          verbose = TRUE, 
                                          config_options = NULL) 
{
    checkmate::assert_character(file_name, null.ok = TRUE, len = 1, 
                                pattern = "^.{1,}$")
    checkmate::assert_character(directory, null.ok = TRUE, len = 1, 
                                pattern = "^.{1,}$")
    checkmate::assert_logical(overwrite, any.missing = FALSE)
    checkmate::assert_character(redcap_uri, any.missing = FALSE, 
                                len = 1, pattern = "^.{1,}$")
    checkmate::assert_character(token, any.missing = FALSE, len = 1, 
                                pattern = "^.{1,}$")
    record <- as.character(record)
    checkmate::assert_character(record, any.missing = FALSE, 
                                len = 1, pattern = "^.{1,}$")
    checkmate::assert_character(field, any.missing = FALSE, len = 1, 
                                pattern = "^.{1,}$")
    validate_field_names(field, stop_on_error = TRUE)
    checkmate::assert_character(event, any.missing = FALSE, len = 1, 
                                pattern = "^.{0,}$")
    checkmate::assert_logical(verbose, any.missing = FALSE)
    token <- sanitize_token(token)
    verbose <- REDCapR:::verbose_prepare(verbose)
    post_body <- list(token = token, content = "file", 
                      action = "export", record = record, field = field, 
                      returnFormat = "csv")
    if (0L < nchar(event)) 
        post_body$event <- event
    if (!is.null(repeat_instrument)) {
        if (is.null(repeat_instance)) {
            stop("You must specify repeat_instance when specified repeat_instrement");
        }
        post_body$repeat_instrument = repeat_instrument;
        post_body$repeat_instance = repeat_instance;
    }
    kernel <- REDCapR:::kernel_api(redcap_uri, post_body, config_options)
    if (kernel$success) {
        result_header <- kernel$result_headers$`content-type`
        if (missing(file_name) | is.null(file_name)) {
            regex_matches <- regmatches(kernel$result_headers, 
                                        regexpr("name=.*", kernel$result_headers))
            file_name <- gsub(pattern = "(name=.)|(\")", 
                              replacement = "", x = regex_matches)
        }
        file_path <- if (missing(directory) & is.null(directory)) {
            file_name
        }
        else {
            file.path(directory, file_name)
        }
        if (verbose) 
            message("Preparing to download the file `", 
                    file_path, "`.")
        if (!overwrite & file.exists(file_path)) {
            stop("The operation was halted because the file `", 
                 file_path, "` already exists and `overwrite` is FALSE.  ", 
                 "Please check the directory if you believe this is a mistake.")
        }
        writeBin(httr::content(kernel$result, as = "raw"), 
                 con = file_path)
        outcome_message <- sprintf("%s successfully downloaded in %0.1f seconds, and saved as %s.", 
                                   result_header, kernel$elapsed_seconds, file_path)
        records_affected_count <- length(record)
        record_id <- as.character(record)
        kernel$raw_text <- ""
    }
    else {
        outcome_message <- "file NOT downloaded."
        records_affected_count <- 0L
        record_id <- character(0)
        file_path <- character(0)
    }
    if (verbose) 
        message(outcome_message)
    list(success = kernel$success, status_code = kernel$status_code, 
         outcome_message = outcome_message, records_affected_count = records_affected_count, 
         affected_ids = record_id, elapsed_seconds = kernel$elapsed_seconds, 
         raw_text = kernel$raw_text, file_name = file_name, file_path = file_path)
}

**Comment by wibeasley** [comment]
@zhangrz2019, this is quite how you submit a pull request with new code.  I'm closing this specific PR, and copying your new code to the right file.  I'll check with you to make sure I'm following correctly.

**Pull request closed without merging**
