### PR TITLE
Adapt for httr 1.0.0

### PR DESCRIPTION
**Pull request by wibeasley**

### CODE REVIEW

**Comment by joshnpowell** [comment]
Thanks @wibeasley for this fix! (Thanks are traveling from just down the road at LIBR.) Any idea when it will make it into CRAN?

**Comment by wibeasley** [comment]
I din't have any plans to update CRAN.  Things seem to change so much (ie, (a) my modifications, (b) httr's improvements, (c) REDCap's improvements) that we've just gotten used to updating from GitHub with `devtools::install_github(repo="OuhscBbmc/REDCapR")`.  But I suppose you're right that this change is important enough to update CRAN.

I'm curious @joshnpowell, does hosting it on CRAN make a difference for you?  I guess it is a lot more convenient to run `update.packages()` once, instead of keeping track of each package that needs it's own GitHub update.

I got scolded last year by a CRAN gatekeeper after submitting an important update 5 weeks later.  I was accused of either being inconsiderate, or incapable of understanding the “no more than every 1–2 months” part in the [CRAN policies](https://cran.r-project.org/web/packages/policies.html).  

I do have a custom solution that works for our machines using https://github.com/OuhscBbmc/OuhscMunge/blob/master/R/package_janitor.R and something like https://github.com/OuhscBbmc/OuhscMunge/blob/master/utility/package_dependency_list.csv).  It helps when we're using fresh packages that CRAN can't keep up with.

**Comment by joshnpowell** [comment]
Hi @wibeasley, thanks for your quick reply. It's a little easier to get the packages from CRAN, and users are a bit more comfortable with "stable" releases. Ultimately, the significant problem in this case was that install_github seems to have some issues with libraries stored on network volumes. We got it to work; just took a little more time. I guess I'd really like to know if there are plans to update CRAN, in which case I might suggest users wait until that happens, if possible.

Sorry you got scolded by CRAN. I get that it could be annoying to have many updates, but 5 weeks looks to be clearly within their window, and they've gotta support users getting good packages!

**Comment by wibeasley** [comment]
For the record, CRAN has just been updated with these changes.  Those using the GitHub version for the past month or two shouldn't notice a difference.  
* https://github.com/OuhscBbmc/REDCapR/releases/tag/0.9.0
* http://cran.r-project.org/web/packages/REDCapR/

**Pull request merged**
