### PR TITLE
Implemented functions for instrument and event-instrument api

### PR DESCRIPTION
**Pull request by vcastro**
Hi Will,

Really excellent package - thanks for making it!

I've implemented functions for the REDCap instruments and formEventMapping (event-instruments) API endpoints that I needed for a project.  I've also included tests for both.  Please have a look.

Thanks,
Victor

### CODE REVIEW

**Comment by wibeasley** [comment]
This is great, @vcastro.  I'm almost done reviewing it.  Can you please tell me your [ORCID number](https://ropensci.org/blog/2018/10/08/orcid/)?  I'd like to add it in the [description file](https://github.com/OuhscBbmc/REDCapR/blob/main/DESCRIPTION).

**Comment by wibeasley** [comment]
@vcastro, thanks for putting so much effort into your new code, and making it consistent with the rest of the package & tests.  This will be easy to maintain in the future.

I made a few minor tweaks --will you please make sure I'm consistent with your intent?  

Also, please send me your email address if you'd like it included in the package description file.

**Comment by wibeasley** [comment]
There's something screwy going on with the GitHub Actions tests.  The errors are unrelated to this PR, and everything is working fine on my other machines.  So I'll merge the PR.  If you'd like, please tell me or add your email & orcid number, @vcastro.  Thanks again.

image

**Comment by vcastro** [comment]
Hi Will,

Great - thanks for reviewing the PR and including it in the package!  My email is vcastro@mgh.harvard.edu and my ORCID id is: 0000-0001-7390-6354.

Thanks,
Victor

**Pull request merged**
